# Makefile for the focaltech touchscreen drivers.

obj-$(CONFIG_TOUCHSCREEN_IRVINE_VZW_FT8756) += touchscreen_ft8756.o
touchscreen_ft8756-y += focaltech_core.o focaltech_ex_fun.o focaltech_ex_mode.o \
	focaltech_gesture.o focaltech_esdcheck.o focaltech_point_report_check.o \
	focaltech_flash.o focaltech_spi.o

